### ISSUE TITLE
Sub directories not working

### ISSUE THREAD

**Issue by drsbaitso** [Fmstrat/shorten#6] opened 2015-02-05 16:20 UTC
If I'm in the root directory, the links get created fine.  As soon as I go into any sub directory, it just gives me the normal share link.

**Comment by drsbaitso** [comment] 2015-02-05 16:31
Ok, appears to be intermittent.  But it only seems to happen on subfolders and sub files... never on the root directory.  That always works.

**Comment by Fmstrat** [comment] 2015-02-05 20:39
Are you running the latest version? And can you let me know what browser you are using?

**Comment by drsbaitso** [comment] 2015-02-05 21:08
Latest version, yes.  Says 0.0.9 in my version file but it's from the 0.0.9-2 release.

FF 35.0.1

**Comment by noisem** [comment] 2015-02-06 08:46
confirm this issue too

**Comment by Fmstrat** [comment] 2015-02-06 15:46
Can one of you try changing js/scripts.js line 6 from:

```
setTimeout(addShareListener, 1000);
```

to:

```
setTimeout(addShareListener, 3000);
```

Then on load and wait a few seconds before moving to a sub-directory, then wait a few seconds to click share? I can't reproduce this and I'm trying to figure out if it's related to the load-time hack I had to create.

**Comment by noisem** [comment] 2015-02-06 16:17
I've did the following:
1. changed the timeout (as you wrote in previous post,  js/scripts.js line 6) 
2. opened my ownCloud, entered user name password
3. shared the link for folder "Folder1" (in the root) and then unshared it - OK
4. entered in "Folder1" and shared the link for folder "Folder2" and then unshared it - OK
5. entered in Folder1\Folder2 and shared the link for folder "Folder3"  - NOT OK, i.e. short link wasn't generated

**Comment by Fmstrat** [comment] 2015-02-16 20:53
Fixed in this commit: https://github.com/Fmstrat/shorten/commit/7f0b169b1fb735fcc66fff700728765e7b26b783

Will be in the next version on apps.owncloud.org today.

**Closed as completed by Fmstrat** 2015-02-16 20:53 UTC
Labels: bug
